version: "3.1"
services:
    webserver:
      image: nginx:alpine
      container_name: gh-blog-nginx
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8030:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: gh-blog-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
        - ./data:/data:rw

    mysql:
      image: mysql:5.7
      container_name: gh-blog-db
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=gh_blog
        - MYSQL_USER=gh_blog
        - MYSQL_PASSWORD=gh_blog
      ports:
        - "8032:3306"